baseurl = "https://adrianabreu.com"
languageCode = "es-ES"
title = "Adrián Abreu"
theme = "kiss"
pagination.pagerSize = 8
copyright = "2017-2024 Adrián Abreu powered by Hugo and Kiss Theme"
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe= true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Adrian Abreu" # Author full name
authorEmail = "adrianabreugonzalez@outlook.com" # Author email

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Adrian Abreu Data Engineering Blog" # Title for home page

[params.social]
twitter = "adrianabreudev"
github = "adrianabreu"
linkedin = "AdrianAbreu"
Email = "adrianabreugonzalez@outlook.com"
 
[permalinks]
post = "/:year/:month/:day/:slug"

[taxonomies]
tag ="tags"

[minify]
disableHTML = true

[params.social.config]
platforms = ["github","twitter","email","linkedin"]